name: fitd24
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  ff_card:
    git:
      url: https://github.com/lohnn/flutter_and_friends_speaker_cards.git
      path: ff_card
  flutter:
    sdk: flutter
  google_fonts: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - path: assets/photos/
    - path: assets/logos/